#!/usr/bin/env bash
# bash script to install Nginx
# /usr/share/nginx/html/index.html

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw -y allow 'Nginx HTTP'
sudo -i
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
