#!/usr/bin/env bash
# bash script that install and configure HAproxy


sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*
echo "frontend web-front
    bind *:80
    default_backend web-backend
backend web-backend
    balance roundrobin
    mode http
    server 944-web-01 35.243.157.160:80 check
    server 944-web-02 34.73.149.36:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restar
