#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times, but 9th iteration displays Holberton school and them Hi on a new line
i=1
while [[ $i -le 10 ]]
do
    echo "Holberton School"
    if [ "$i" -eq "9" ]
    then
	echo "Hi"
    fi
    i=$(( i + 1 ))
done
